/**
 * Sample data for initial app setup
 */

import { Equipment, ServiceRecord, FuelLog, LubricationPoint, SparePart, FuelStock } from "@/types";

export const SAMPLE_EQUIPMENT: Equipment[] = [
  {
    id: "mixer-001",
    name: "Mješalica za Beton",
    type: "mixer",
    displayName: "Mješalica za Beton (Elkon)",
    currentHours: 250,
    serviceIntervalHours: 250,
    lastServiceHours: 0,
    lastServiceDate: "2025-11-15",
    fuelEfficiency: 0,
    status: "good",
  },
  {
    id: "loader-001",
    name: "Utovarivač",
    type: "loader",
    displayName: "Utovarivač (Hyundai)",
    currentHours: 150,
    serviceIntervalHours: 250,
    lastServiceHours: 0,
    lastServiceDate: "2025-11-20",
    fuelEfficiency: 12, // L/hour
    fuelLevel: 85, // Current fuel in tank
    fuelCapacity: 150, // Tank capacity
    status: "good",
  },
  {
    id: "generator-001",
    name: "Generator",
    type: "generator",
    displayName: "Generator",
    currentHours: 100,
    serviceIntervalHours: 200,
    lastServiceHours: 0,
    lastServiceDate: "2025-11-25",
    fuelEfficiency: 8, // L/hour
    fuelLevel: 280, // Current fuel in tank
    fuelCapacity: 540, // Tank capacity
    status: "good",
  },
];

export const SAMPLE_SERVICE_RECORDS: ServiceRecord[] = [
  {
    id: "srv-001",
    equipmentId: "mixer-001",
    date: "2025-11-15",
    hoursAtService: 0,
    serviceType: "Zamjena ulja",
    partsUsed: ["part-001", "part-003"],
    cost: 85,
    technician: "Interni",
    notes: "Početni servis",
  },
  {
    id: "srv-002",
    equipmentId: "loader-001",
    date: "2025-11-20",
    hoursAtService: 0,
    serviceType: "Servis 250h",
    partsUsed: ["part-002", "part-003"],
    cost: 150,
    technician: "Hyundai Servis",
    notes: "Redovno održavanje",
  },
  {
    id: "srv-003",
    equipmentId: "generator-001",
    date: "2025-11-25",
    hoursAtService: 0,
    serviceType: "Zamjena ulja",
    partsUsed: ["part-003"],
    cost: 65,
    technician: "Interni",
    notes: "Rutinski servis",
  },
];

export const SAMPLE_FUEL_LOGS: FuelLog[] = [
  {
    id: "fuel-001",
    equipmentId: "loader-001",
    date: "2025-12-15",
    litersAdded: 50,
    costPerLiter: 1.2,
    totalCost: 60,
    hoursAtFueling: 150,
    notes: "Redovna dopuna",
  },
  {
    id: "fuel-002",
    equipmentId: "generator-001",
    date: "2025-12-14",
    litersAdded: 30,
    costPerLiter: 1.2,
    totalCost: 36,
    hoursAtFueling: 100,
    notes: "Dopuna prije radnog dana",
  },
];

export const SAMPLE_LUBRICATION_POINTS: LubricationPoint[] = [
  {
    id: "lub-001",
    name: "Ležajevi bubnja mješalice",
    type: "Mast",
    frequency: "weekly",
    equipmentId: "mixer-001",
    lastCompleted: "2025-12-15",
    nextDue: "2025-12-22",
    status: "good",
  },
  {
    id: "lub-002",
    name: "Reduktor mješalice",
    type: "Provjera ulja",
    frequency: "weekly",
    equipmentId: "mixer-001",
    lastCompleted: "2025-12-15",
    nextDue: "2025-12-22",
    status: "good",
  },
  {
    id: "lub-003",
    name: "Čepovi kašike utovarivača",
    type: "Mast",
    frequency: "daily",
    equipmentId: "loader-001",
    lastCompleted: "2025-12-17",
    nextDue: "2025-12-18",
    status: "good",
  },
  {
    id: "lub-004",
    name: "Zglobovi strele utovarivača",
    type: "Mast",
    frequency: "daily",
    equipmentId: "loader-001",
    lastCompleted: "2025-12-17",
    nextDue: "2025-12-18",
    status: "good",
  },
  {
    id: "lub-005",
    name: "Valjci transportera",
    type: "Mast",
    frequency: "weekly",
    lastCompleted: "2025-12-15",
    nextDue: "2025-12-22",
    status: "good",
  },
  {
    id: "lub-006",
    name: "Lanac transportera",
    type: "Ulje",
    frequency: "weekly",
    lastCompleted: "2025-12-15",
    nextDue: "2025-12-22",
    status: "good",
  },
];

export const SAMPLE_SPARE_PARTS: SparePart[] = [
  {
    id: "part-001",
    name: "Filter ulja motora",
    partNumber: "OF-2540",
    equipment: "loader",
    currentStock: 3,
    minimumLevel: 2,
    price: 15.5,
    supplier: "Hyundai",
    status: "adequate",
  },
  {
    id: "part-002",
    name: "Hidraulični filter",
    partNumber: "HF-6380",
    equipment: "loader",
    currentStock: 2,
    minimumLevel: 2,
    price: 28,
    supplier: "Hyundai",
    status: "adequate",
  },
  {
    id: "part-003",
    name: "Filter vazduha",
    partNumber: "AF-1250",
    equipment: "generator",
    currentStock: 4,
    minimumLevel: 2,
    price: 22,
    supplier: "Generator Parts",
    status: "adequate",
  },
  {
    id: "part-004",
    name: "Filter goriva",
    partNumber: "FF-5320",
    equipment: "generator",
    currentStock: 3,
    minimumLevel: 2,
    price: 18.5,
    supplier: "Generator Parts",
    status: "adequate",
  },
  {
    id: "part-005",
    name: "Lopatica mješalice",
    partNumber: "MB-450",
    equipment: "mixer",
    currentStock: 2,
    minimumLevel: 1,
    price: 85,
    supplier: "Elkon",
    status: "adequate",
  },
  {
    id: "part-006",
    name: "Traka transportera",
    partNumber: "CB-1200",
    equipment: "mixer",
    currentStock: 1,
    minimumLevel: 1,
    price: 320,
    supplier: "Elkon",
    status: "adequate",
  },
  {
    id: "part-007",
    name: "Mast (patrona)",
    partNumber: "GR-NLGI2",
    equipment: "all",
    currentStock: 12,
    minimumLevel: 5,
    price: 4.5,
    supplier: "General",
    status: "adequate",
  },
  {
    id: "part-008",
    name: "Motorno ulje 15W40 (20L)",
    partNumber: "OIL-15W40",
    equipment: "all",
    currentStock: 40,
    minimumLevel: 20,
    price: 65,
    supplier: "Oil Supplier",
    status: "adequate",
  },
  {
    id: "part-009",
    name: "Hidraulično ulje (20L)",
    partNumber: "HYD-ISO46",
    equipment: "loader",
    currentStock: 20,
    minimumLevel: 20,
    price: 75,
    supplier: "Oil Supplier",
    status: "adequate",
  },
  {
    id: "part-010",
    name: "V-remen",
    partNumber: "V-BELT-A",
    equipment: "mixer",
    currentStock: 4,
    minimumLevel: 2,
    price: 12,
    supplier: "Elkon",
    status: "adequate",
  },
  {
    id: "part-011",
    name: "Pneumatski ventil",
    partNumber: "SOL-24V",
    equipment: "all",
    currentStock: 3,
    minimumLevel: 2,
    price: 45,
    supplier: "General",
    status: "adequate",
  },
];

export const SAMPLE_FUEL_STOCK: FuelStock = {
  id: "fuel-stock-001",
  currentLiters: 2500,
  capacity: 5000,
  minimumLevel: 1000,
  lastUpdated: new Date().toISOString(),
  notes: "Glavna boca goriva na lokaciji",
};
